'use strict';

// import './images/slider/food-12.jpg';
// import basicScene from './js/lessons/basic-scene';
// import lessonGeometries from './js/lessons/geometries';
// import lessonTextures from './js/lessons/lesson-textures';
// import lessonText from './js/lessons/lesson-text';
// import lessonLights from './js/lessons/lesson-lights';
// import lessonHautedHouse from './js/lessons/haunted-house';
// import lessonParticles from './js/lessons/lesson-particles';
// import galaxy from './js/lessons/galaxy';
// import './js/lessons/physics';
import './js/lessons/shaders';
// import importModels from './js/lessons/import-models';
// import lRaycaster from './js/lessons/raycaster';
// import realisticRender from './js/lessons/realistic-render';
// import lPostprocessing from './js/lessons/lpostprocessing';
// import lLoader from './js/lessons/l-loader';
import './scss/main.scss';

// basicScene();
// lessonGeometries();
// lessonTextures();
// lessonText();
// lessonLights();
// lessonHautedHouse();
// lessonParticles();
// galaxy();
// importModels();
// lRaycaster();
// realisticRender();
// lPostprocessing();
// lLoader();